on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  quality_check:
    name: "quality check"
    runs-on: "ubuntu-latest"
    steps:
      #get access to repo
      - name: "get repo"
        uses: actions/checkout@v6
        
      #install python
      - name: "install python"
        uses: actions/setup-python@v6
      
      #install libraries
      - name: "install libaries"
        run: pip3 install -r requirements.txt
        
      #run pytest/pylint
      - name: "run pylint and pytest"
        run: pytest
      
    
      
